spring.application.name=backend

# Kết nối trực tiếp đến TiDB Cloud (MySQL-compatible)
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/todo_list?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=p8ER2BDgixMh7mX.root
spring.datasource.password=DGjA1FvOqifiUcCf
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
